version: '2.2'
services:
  minio:
    image : "minio/minio"
    container_name : minio
    environment:
      - "MINIO_ACCESS_KEY=minio"
      - "MINIO_SECRET_KEY=minio123"
    
    command: server /data
    ports: 
      - "9000:9000"
    stdin_open : true

    tty : true
    
  
  toxiproxy:
           image : "shopify/toxiproxy"
           container_name : toxiproxy
           network_mode: host
           
  spark1:
        build : ./spark1/

  
        network_mode: host

        stdin_open : true

        tty : true
        
        container_name : spark1
        #command: python /usr/spark-2.4.1/bin/init.py ; /bin/bash
  
  spark2:
        build : ./spark2/

        network_mode: host

        stdin_open : true

        tty : true

        container_name : spark2
        
        #command: python /usr/spark-2.4.1/bin/init.py ; /bin/bash
  spark3:
        build : ./spark3/
                 
        network_mode: host

        stdin_open : true

        tty : true
        
        container_name : spark3
 